using Interfacer;
using NUnit.Framework;
using Test.Autogenerate;
using Test.TestClasses;

namespace Test.Fixtures
{
    [TestFixture]
    public class AutogenerateFixture
    {
        [Test]
        public void VerifyAutogeneratedFrameworkInterfaceShouldSucceed()
        {
            Assert.That(InterfacerFactory.Verify<IProcess>, Throws.Nothing);
        }

        [Test]
        public void VerifyAutogeneratedInterfaceShouldSucceed()
        {
            Assert.That(InterfacerFactory.Verify<ITestObjectAuto>, Throws.Nothing);
        }

        [Test]
        public void VerifyAutogeneratedInterfaceWithGenericsShouldSucceed()
        {
            Assert.That(() => InterfacerFactory.Verify(typeof(ITestObjectWithGenericTypesAuto<,>)), Throws.Nothing);
        }
    }
}
